keep-open=yes
# Wayland compositor may be trying to apply an HDR or wide-gamut profile as soon as a window goes fullscreen.
# Try disabling the "target colorspace hint" which tells the system to stop trying to be "smart" about the colors in fullscreen:
target-colorspace-hint=no

osc=no # need for ModernZ
title-bar=no
