# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      CommitMono Nerd Font
bold_font        CommitMono Nerd Font Bold
italic_font      CommitMono Nerd Font Italic
bold_italic_font CommitMono Nerd Font Bold Italic

font_size 13.0

#: Font size (in pts).

#: }}}

# hide_window_decorations titlebar-only

include cyberdream.conf
